---
language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.2
  - 2.3.0
os:
- linux
- osx

matrix:
  allow_failures:
  # https://github.com/travis-ci/travis-ci/issues/5361
  - os: osx
    rvm: 2.3.0
