# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ffmpeg-video-info 0.2.3 ruby lib
# stub: ext/ffmpeg_video_info_ext/extconf.rb

Gem::Specification.new do |s|
  s.name = "ffmpeg-video-info"
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Pavel Tatarsky"]
  s.date = "2015-07-13"
  s.description = "It only provides gathering info about media files"
  s.email = "fazzzenda@mail.ru"
  s.extensions = ["ext/ffmpeg_video_info_ext/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ext/ffmpeg_video_info_ext/extconf.rb",
    "ext/ffmpeg_video_info_ext/ffmpeg_video_info_ext.c",
    "ffmpeg-video-info.gemspec",
    "lib/ffmpeg_video_info.rb",
    "spec/fixtures/test.mp4",
    "spec/lib/info_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/vintikzzz/ffmpeg-video-info"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.7"
  s.summary = "Ruby binding for FFmpeg library"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<rice>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rake-compiler>, [">= 0"])
      s.add_development_dependency(%q<mini_portile>, [">= 0"])
    else
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<rice>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rake-compiler>, [">= 0"])
      s.add_dependency(%q<mini_portile>, [">= 0"])
    end
  else
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<rice>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rake-compiler>, [">= 0"])
    s.add_dependency(%q<mini_portile>, [">= 0"])
  end
end

